### PR TITLE
add python 3 encoding notice to output.md

### PR DESCRIPTION
**Pull request by Larivact**

### CODE REVIEW

**Comment by Larivact** [comment]
Interestingly not only
`file = open(name, 'wb'); file.write(fpdfOutput.encode('latin-1')); file.close()` but also
`file = open(name, 'w'); file.write(fpdfOutput); file.close()` produce exactly the same valid PDF. (used Python version 3.3.0)

So it seems like you only have to worry about it if you want to send the PDF over HTTP. Because if you do so it will end up as 'bytes' one way or another. I am pretty confused how the file.write method is able to autodetect the encoding.

**Comment by RomanKharin** [comment]
That's right. Probably some mode (s**T**ream, **H**ttp, or any other letter) should be added, so
```
...
elif dest=='H':
    name.write(buffer)
...
```

**Comment by Larivact** [comment]
I would rather go with a `output_bytes` method.

**Comment by vadmium** [comment]
I think that workaround was required for older versions, but not with the current master branch. See PR #14.

```python
>>> type(pdf.output(dest="S"))
<class 'bytes'>
>>> pdf.output(dest="S").encode("latin-1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by RomanKharin** [comment]
Hmm, HEAD already do this at line 112.
My fault. 
We should create new release.

**Comment by Larivact** [comment]
Yeah I installed it via `pip`. But probably you should keep that notice and add that it got fixed with version xyz? I mean some people will still use an older version and run into this problem.

**Comment by vadmium** [comment]
Is there much legacy Python 3 code depending on this? In the 1.7.2 readme, Python 3 support was said to be experimental. I imagine most legacy code would be Python 2, where output() does return a byte string (not a Unicode string).

**Comment by Larivact** [comment]
>Is there much legacy Python 3 code depending on this?

Probably not. I just don't like having to pass unintuitive arbitrary letters. IMO the output method shouldn't take have any parameters and just return 'bytes' or a 'str' depending on what python version you're using. If you want to print it you can do it yourself, if you want to write it to a file you can do it yourself. What you do with the generated PDF really is none of PyFPDF's business.

I like the UNIX philosophy "Do one thing, and do it well.". That way things stay transparent and clean.

**Comment by vadmium** [comment]
I completely agree with you about the output() function trying to do too many things, and wouldn’t be against adding straightforward output_bytes() alternative.

**Pull request merged**
