### PR TITLE
Changing latin1 encodings into windows-1252

### PR DESCRIPTION
**Pull request by nklever**
Changing latin-1 encodings into windows-1252, because "Windows-1252" includes either ISO8859-1 (latin1) and ISO8859-15 (latin9), so Windows-1252 is the best choice for the built-in fonts.
see [Wikipedia: Western Latin Character Sets](https://en.wikipedia.org/wiki/Western_Latin_character_sets_%28computing%29), especially item 3 in the summary

### CODE REVIEW

**Comment by RomanKharin** [comment]
Seems to be this change csn lead to malformed pdfs. PDF specification 1.7 ann D describe only latin-1 part for 12 standard fonts of 14.

**Comment by RomanKharin** [comment]
Additional links http://stackoverflow.com/questions/10866240/adobe-font-metrics-for-standard-pdf-fonts-in-cp1252

**Comment by RomanKharin** [comment]
Also i should note that ann D specify possibility for western charters, but not for standard encodind we used for now.

**Comment by RomanKharin** [comment]
I just commit new test to our test suite cover/test_e1252.py
This test show all available charters in cp1252 according to PDF 1.7 specification (and some more).
As you can see proposed change allow to use few charters
1. Euro \u20AC -> \x80
2. OE  \u0152 -> \x8C
3. Scaron \u0160 -> \x8A
4. Ydieresis \u0178 -> \x9F
5. Zcaron \u017d -> \x8E
6. bullet \u2022 -> \x95
7. circumflex \u02C6 -> \x88
8. dagger \u2020 -> \x86
9. daggerdbl \u2021 -> \x87
10. ellipsis  \u2026 -> \x85
11. emdash  \u2014 -> \x97
12. endash \u2013 -> \x96
13. florin \u0192 -> \x83
14. guilsinglleft \u2039 -> \x8B
15. guilsinglright \u203A -> \x9B
16. oe \u0153 -> \x9C
17. perthousand \u2030 -> \x89
18. quotedblbase \u201E -> \x84
19. quotedblleft \u201C -> \x93 
20. quotedblright \u201D -> \x94
21. quoteleft \u2018 -> \x91
22. quoteright \u2019 -> \x92
23. quotesinglbase \u201A -> 0x82
24. scaron \u0161 -> \x9A
25. tilde \u02DC -> \x98
26. trademark \u2122 -> \x99
27. zcaron \u017E -> \x9E

And some diacritics charters, which currently didn't work as expected. WinAnsi is not so universal as it would be (L-slash etc). All these charters will be shown with good unicode font.

Also this change will not work for python3.

Is anyone have suggestions about:
Should we change default behavior and allow automatic conversion for default non-embedded fonts or not?
Python3 support for this can be added later, but with some time increasing.

**Comment by nklever** [comment]
Thanks for your test, my test ([test_encoding_problems.py](https://github.com/nklever/pyfpdf/blob/master/tests/cover/test_encoding_problems.py)) was only a slight adaption to the test_unicode.py file. It takes the same characters from PDF specification 1.7 Annex D as your test, but gets UnicodeEncodeErrors if you don't use the suitable text. But in general it came to the same result of the above 27 characters.

**Comment by RomanKharin** [comment]
Hi, nklevel.
I just modify test_e1252 to show all glyphs in wiki-like manner (on the last page).  Also i have to fix some glyph codes (macron, cedilla etc. Python did do "\u0020\u0304" -> "\xAF" conversion directly without unicode.normalize).

With this ugly hack
```
txt = txt.encode("windows-1252").decode("latin-1")
```
all 1252 glyphs can be represented.
But IMHO we can do better. We can add `pdf.set_corefont_encoding(enc)` or `pdf.set_doc_option("corefont_encoding", "windows-1252")`. Later as part of new API additions.
This way allow:
1. Preserve 100% compatibility
2. Allow to use any unicode->byte mapper

**Comment by nklever** [comment]
Yes, the API extension seems to me a very good idea - I would appreciate it !

**Comment by RomanKharin** [comment]
Hi to all,
Just commited new api:
```
    pdf.set_doc_option("core_fonts_encoding", "windows-1252")
```
This works for both 2.7 and 3.4+ versions. Documentation on readthedocs somewhat stalled, please wait or check on github directly.

**Comment by RomanKharin** [comment]
My fault, fix all with https://github.com/reingart/pyfpdf/commit/8b6481f0bf5089fb6dad9c1b96d42ad3d9321f68

**Pull request closed without merging**
