### PR TITLE
always returning a string when output(dest=S)

### PR DESCRIPTION
**Pull request by tramwaj29**
fast fix as we always want to return a string here and not bytes

### CODE REVIEW

**Comment by vadmium** [comment]
I’m not sure I agree. Why do you want the PDF data as a text string?

PDF data may contain non-ASCII bytes as far as I understand and remember, such as bytes in Latin-1 or UTF-16 encoding, or even random compressed data. It is stored internally as a Latin-1 text string, but that is just a hacky artifact of porting from Python 2 to 3 I think.

**Comment by tramwaj29** [comment]
Well either way, I think that we should always return the same type; since the comment says that it's returning a string it seems very misleading to me that sometimes we would return bytes and sometimes a string

**Comment by vadmium** [comment]
I agree the comment is misleading. Perhaps I could change it to say “byte string” instead.

**Comment by tramwaj29** [comment]
Yeah, you're right sorry for the mess ;)

**Comment by RomanKharin** [comment]
Hi to all. Thanks for contributing
We already note in doc that outpus(.., "S") gives bytes (as for py3+) http://pyfpdf.readthedocs.org/en/latest/reference/output/index.html
```
S: return the document as a byte string.
```
So this commit will fix only comment.
Note: JJ, i can't merge this until #43 merged

**Comment by vadmium** [comment]
Hello @tramwaj29, I cherry-picked your change to the comment and pushed that, so hopefully all is good now

**Comment by vadmium** [comment]
Pushed in revision 567aed3

**Pull request closed without merging**
