### PR TITLE
Handle JPEG images without PIL

### PR DESCRIPTION
**Pull request by craigahobbs**
This change enables insertion of JPEG images without PIL.  Test output was the same before and after.  Let me know if you have any questions.

### CODE REVIEW

**Comment by reingart** [comment]
Ok, as second commit is harmless, at first, I don't see any inconvenience on merging this one.
I've to take a closer look, but could'n we have the two methods? 
(with and without PIL, so in the former, if something is unsupported, we don't affect the users that already had PIL installed)
BTW, @craigahobbs: could you provide a simple test or similar to speed up the process?

**Comment by craigahobbs** [comment]
I was thinking it would be best to not use PIL for JPEG - that way you'll get the same results whether you have PIL installed or not.  FYI I created the patch to avoid the buildout on PIL which was turning out to be a real headache.  Let me know if you want me to add the PIL path back.  Once I hear back I'll add a test or two.

**Comment by reingart** [comment]
PIL is still required to parse GIF, right? (in fact, it seems to be used to convert it to PNG)

I'm not sure about the buildout issue, but if you are more confident in this code, and it handles all JPG use cases, I think we could merge this patch.

Thanks again for you collaboration!

**Comment by reingart** [comment]
Ok, if you can add the test for this commit, that would be great (maybe for the three colspace: 'DeviceRGB', 'DeviceCMYK' and 'DeviceGray')
If anyone else sees any objection, I think this PR could be merged then

**Comment by RomanKharin** [comment]
Just pushed new test for embedding jpeg images in main repo, will wait this patch too.
hint to run: python cover/test_jpeg.py

**Pull request merged**
