### PR TITLE
Ignore encoding errors when encoding PY3 pages

### PR DESCRIPTION
**Pull request by thinkwelltwd**
Had problems with UnicodeEncodeErrors. Setting errors to "ignore" fixes the issue.  I suppose the param could be controlled with a class variable too...

### CODE REVIEW

**Comment by RomanKharin** [comment]
HI, thinkwelltwd
Can you provide exmaple when this failed without ignore argument.
I used this error as symptom of bad code when porting to Py3 .

**Comment by thinkwelltwd** [comment]
Here's the relevant part of a traceback.

File "/usr/lib/python3.4/site-packages/fpdf/fpdf.py", line 1065, in output
self.close()
File "/usr/lib/python3.4/site-packages/fpdf/fpdf.py", line 246, in close
self._enddoc()
File "/usr/lib/python3.4/site-packages/fpdf/fpdf.py", line 1636, in _enddoc
self._putpages()
File "/usr/lib/python3.4/site-packages/fpdf/fpdf.py", line 1170, in _putpages
p = self.pages[n].encode("latin1") if PY3K else self.pages[n]
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 8355: ordinal not in range(256)

**Comment by RomanKharin** [comment]
But it should not been receive charters > 255. Error(s) are somewhere before
Can you create small program to expose this error?

**Comment by thinkwelltwd** [comment]
Why is a valid UTF8 character an error? I'm not following you on that. I'm working with log files in UTF8 encoding, so it's quite possible to have some characters that'll squished when encoding to latin1, and a traceback is not at all the response I'm looking for.

Are you saying that it would be better to convert to latin1 or perhaps even bytes before feeding the data to fpdf?

**Comment by RomanKharin** [comment]
Due pdf and python specific all unicode codepoints are encoded with utf-16 and represented as latin-1 codeset. If you encounter unicode charters in main glue function this is error.

**Comment by thinkwelltwd** [comment]
Well, I just ran my input file through the UTF8ToUTF16BE function without incident so I guess the issue isn't in the input data. 

Yes, well. This is a legacy codebase that I'm supporting and due to be replaced. Till then, I have my hack and you have a bug-free project.

Thanks for fpdf!

**Comment by RomanKharin** [comment]
It is very handy to find what data can be processed that way via our encode function (which i suppose suboptimal) and fix that. We have a leak?

**Comment by RomanKharin** [comment]
Thinkwelltwd, can you pm me that text?

**Comment by reingart** [comment]
Converting to UTF8ToUTF16BE will make no difference in general (assuming the file is being read in the correct final encoding and the font used supports all the characters to be displayed).

u'\u2013' is a dash – and cannot be represented in latin1 default built-in PDF standard fonts.

normalize_text should handle this cases, maybe the text is being added with a non-standard FPDF method or core_fonts_encoding is not set. 

Adding an "ignore" could add even more hard-to-detect issues.
Agreed that the traceback is not user-friendly in this case, maybe more checks should be add to normalize_text and other functions to assert that no character reach the internal buffer "unencoded" (anyway, it's currently raises unicode errors when trying to add text in an unsupported encoding for the font/settings)

A minimal test case could have been more helpful, see for example the attached [issue45.zip](https://github.com/reingart/pyfpdf/files/89918/issue45.zip)

Closing this as it cannot be reproduced.

**Pull request closed without merging**
