### PR TITLE
Update fpdf.py

### PR DESCRIPTION
**Pull request by vyscond**
for some reason the ```del info['data']``` was raising an __KeyError__, so i think it's better check before deleting?

### CODE REVIEW

**Comment by RomanKharin** [comment]
Ramon, can you write here example when this error appeared. What version of PIL/Pillow you've used.
'data' member of dict are produced by _parsejpg, _parsegif, _parsepng and only way when it's is not on are library error.

**Comment by vyscond** [comment]
This my custom class

```python
class MyPDF(FPDF):

    def header(this):
        # Logo
        this.image('app_folder/logo1.jpg',10,10,12,12)
        this.image('app_folder/logo2.jpg',190,10,12,12)
        # Arial bold 15
        this.set_font('Arial','',9)
        # Move to the right
        this.cell(80)
        # Title
        this.cell(30,4,'Document Title',0,0,'C')
        # Line break
        this.ln(20)

    # Page footer
    def footer(this):
        # Position at 1.5 cm from bottom
        this.set_y(-15)
        # Arial italic 8
        this.set_font('Arial','I',8)
        # Page number
        this.cell(0,10,'Página '+str(this.page_no())+'/{nb}',0,0,'C')
        this.alias_nb_pages()
```

and here is how i use it.

```python
pdf = MyPDF()
pdf.add_page()
pdf.set_font('Arial','B',16)
pdf.cell(40,10,'Section Title')
pdf.ln()
pdf.set_font('Arial','',12)
pdf.multi_cell(0,mclh, big_text )
```

whats is strange is that i checked the logs from yesterday and the __image__ function just worked fine with the same __.jpg__ files. The error popup today! .-.

**Comment by RomanKharin** [comment]
Sorry, no errors. (Python 2.7, 3.3, 3.4 with/without PIL/Pillow)
Which versions you use?
I used img_gray.jpg and img_rgb.jpg instead of logo1.jpg and logo2.jpg

Please check if did you called pdf.output twice?

**Comment by vyscond** [comment]
Yeah. You are write. I was calling __output__ function twice.

**Pull request closed without merging**
